language: go
sudo: required

go:
  - 1.12

env:
    - GO111MODULE=auto

before_install:
    - go get github.com/mattn/goveralls
    - Project=apollo

install:
  - go get

script:
    - chmod u+x coverage.sh
    - ./coverage.sh --coveralls
    - go build -o "$Project"
